---
title: "Stat_tests"
output: html_document
date: "2022-12-03"
---

```{r setup}
library(tidyverse)

```

```{r}
df1 <- read_csv('fossil-fuel-primary-energy.csv')
df1
```

```{r}
colnames(df1)
df1 %>% select(Year) %>% summarise(max(Year))
```

```{r}
df1 %>% select(Entity) %>% unique()
```
```{r}
continents <- read_csv('countries_continents.csv')
continents
```
``` {r}
df1 <-  inner_join(df1, continents, by=c('Entity'='Country'))
df1
```
``` {r}
df1 %>% filter(Year=='2021') %>% group_by(Continent) %>% summarise(n=n(), mean_Fossil_fuels_TWh=mean(`Fossil fuels (TWh)`), s = sd(`Fossil fuels (TWh)`))
```

```{r}
df1 %>% filter(Year=='2021') %>% arrange(Continent)
```
```{r}
df1 %>% filter(Year=='2021') %>% #arrange(Continent) %>% 
  summarise(n=n(), mean_Fossil_fuels_TWh=mean(`Fossil fuels (TWh)`))
```
``` {r}
df1 %>% filter(Continent=="North America") %>% select(Entity) %>% unique()
```

``` {r}
out <- aov(formula = `Fossil fuels (TWh)` ~ Continent, data = df1 %>% filter(Year=='2021'))
summary(out)
```
``` {r}
df1 %>% filter(Year=='2021') %>% 
  ggplot() + geom_boxplot(aes(`Fossil fuels (TWh)`, Continent)) + 
  scale_x_continuous(breaks = round(seq(0, 20000, by = 5000),1), limits=c(0,20000)) + 
  xlab('Fossil fuels (TWh)')
```
```{r}
df_1 <- 5
df_2 <- 51
x <- seq(from = 0, to = 5, length.out = 5000)
px <- df(x, df_1,df_2)
plot(x, px, type = 'l', lwd = 2,
     main = "PDF for F Distribution with df1 = 5 and df2 = 51")
polygon(append(x[x>1.355], 1.355, after = 0), append(px[x>1.355], 0, after=0), col = "#65BFFF")
```
